### ISSUE TITLE
vagrant environment - how to setup properly VMs

### ISSUE THREAD

**Issue by Gainutdinov** [PacktPublishing/Learning-Ansible-2.X-Third-Edition#1]
Dear Author, 
could you please update **Vagrantfile**s in order to be able to follow your instruction from the book,
I deployed VM from Chapter02 but when swithced to Chapter03 there is no word about the communication between previous test01.fale.io VM and 3 new VMs ws01.fale.io,ws02.fale.io,db01.fale.io.

I was trying to use test01.fale.io as a ansible master server but still due to lack of info or VM misconfiguration cannot follow the instruction from the book :(

**Comment by Fale** [comment]
Hi @Gainutdinov, what kind of problem are you facing? Is it a network issue?

**Comment by Gainutdinov** [comment]
Hi @Fale I already forgot about the problem, I will let you know if face it again, thank you!
